import modal
import requests
import Udio
import Udio.hcaptcha

datascience_image = (
    modal.Image.debian_slim()
    .pip_install("requests", "undetected_chromedriver")
)

app = modal.App(name="example-lifecycle-web2")

@app.function(image=datascience_image)
@modal.web_endpoint(method="POST", docs=True)
def get_audio(data: dict) -> str:
    return get_audio_from_udio_and_selenium.local(data)
    #return "hello"

@app.function(image=datascience_image)
def get_audio_from_udio_and_selenium(data: dict) -> str:
    prompt = data.get("prompt")     

    captcha_token = Udio.hcaptcha.get_captcha()

    final_song_url = Udio.generate_song_sequence(
        auth_token0 = "base64-eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0ltdHBaQ0k2SWxKSFZrdG9Wek5OY1NzeVZ6aHhjRGtpTENKMGVYQWlPaUpLVjFRaWZRLmV5SmhZV3dpT2lKaFlXd3hJaXdpWVcxeUlqcGJleUp0WlhSb2IyUWlPaUp2WVhWMGFDSXNJblJwYldWemRHRnRjQ0k2TVRjeU16WTBOakF5TkgxZExDSmhjSEJmYldWMFlXUmhkR0VpT25zaWNISnZkbWxrWlhJaU9pSmthWE5qYjNKa0lpd2ljSEp2ZG1sa1pYSnpJanBiSW1ScGMyTnZjbVFpWFgwc0ltRjFaQ0k2SW1GMWRHaGxiblJwWTJGMFpXUWlMQ0psYldGcGJDSTZJbUp2Y25semIyWm1NakZBWjIxaGFXd3VZMjl0SWl3aVpYaHdJam94TnpJek56RTRPVFUyTENKcFlYUWlPakUzTWpNM01UVXpOVFlzSW1selgyRnViMjU1Ylc5MWN5STZabUZzYzJVc0ltbHpjeUk2SW1oMGRIQnpPaTh2YldadGNIaHFaVzFoWTNOb1ptTndlbTl6YkhVdWMzVndZV0poYzJVdVkyOHZZWFYwYUM5Mk1TSXNJbkJvYjI1bElqb2lJaXdpY205c1pTSTZJbUYxZEdobGJuUnBZMkYwWldRaUxDSnpaWE56YVc5dVgybGtJam9pTkRkbE9UaGpPVFF0TURaalpTMDBNakJpTFRnNU4yTXRORGRpT0dFek0ySTFOelk0SWl3aWMzVmlJam9pT1dNMk9UZzVabUl0TWpZMU9DMDBaamRoTFRoaE9UZ3RaV1ExWVRNd1pEWTBNbU0wSWl3aWRYTmxjbDl0WlhSaFpHRjBZU0k2ZXlKaGRtRjBZWEpmZFhKc0lqb2lhSFIwY0hNNkx5OWpaRzR1WkdselkyOXlaR0Z3Y0M1amIyMHZaVzFpWldRdllYWmhkR0Z5Y3k4d0xuQnVaeUlzSW1OMWMzUnZiVjlqYkdGcGJYTWlPbnNpWjJ4dlltRnNYMjVoYldVaU9pSkNiM0o1YzJWdWEyOGdWbTkyWVNBb1ZVRXBJRVJsYkdWbllYUmxJbjBzSW1WdFlXbHNJam9pWW05eWVYTnZabVl5TVVCbmJXRnBiQzVqYjIwaUxDSmxiV0ZwYkY5MlpYSnBabWxsWkNJNmRISjFaU3dpWm5Wc2JGOXVZVzFsSWpvaVltOXllWE5sYm10dmRtOXNiMlI1YlhseUlpd2lhWE56SWpvaWFIUjBjSE02THk5a2FYTmpiM0prTG1OdmJTOWhjR2tpTENKdVlXMWxJam9pWW05eWVYTmxibXR2ZG05c2IyUjViWGx5SXpBaUxDSnVaV1ZrYzE5dmJtSnZZWEprYVc1bklqcDBjblZsTENKdVpYZGZkWE5sY2lJNmRISjFaU3dpY0dodmJtVmZkbVZ5YVdacFpXUWlPbVpoYkhObExDSndhV04wZFhKbElqb2lhSFIwY0hNNkx5OWpaRzR1WkdselkyOXlaR0Z3Y0M1amIyMHZaVzFpWldRdllYWmhkR0Z5Y3k4d0xuQnVaeUlzSW5CeWIzWnBaR1Z5WDJsa0lqb2lOamc0TXpZd05ETTVNalF5T1RRNE5qTTNJaXdpYzNWaUlqb2lOamc0TXpZd05ETTVNalF5T1RRNE5qTTNJbjBzSW5WelpYSmZjbTlzWlNJNmJuVnNiSDAuVEl4ejJISkRIRDJnc1h2X2NOQ1NzZXhZS0wwTUtrbk1vYkl4a0VTeC1ZMCIsInRva2VuX3R5cGUiOiJiZWFyZXIiLCJleHBpcmVzX2luIjozNjAwLCJleHBpcmVzX2F0IjoxNzIzNzE4OTU2LCJyZWZyZXNoX3Rva2VuIjoiZVFLZE80SnN2RW1VMWdoZGllUXRXdyIsInVzZXIiOnsiaWQiOiI5YzY5ODlmYi0yNjU4LTRmN2EtOGE5OC1lZDVhMzBkNjQyYzQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJlbWFpbCI6ImJvcnlzb2ZmMjFAZ21haWwuY29tIiwiZW1haWxfY29uZmlybWVkX2F0IjoiMjAyNC0wOC0xNFQwOToyOTozMS43NjgxMloiLCJwaG9uZSI6IiIsImNvbmZpcm1lZF9hdCI6IjIwMjQtMDgtMTRUMDk6Mjk6MzEuNzY4MTJaIiwibGFzdF9zaWduX2luX2F0IjoiMjAyNC0wOC0xNFQxNDozMzo0NC42ODAzMDNaIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZGlzY29yZCIsInByb3ZpZGVycyI6WyJkaXNjb3JkIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9lbWJlZC9hdmF0YXJzLzAucG5nIiwiY3VzdG9tX2NsYWltcyI6eyJnbG9iYWxfbmFtZSI6IkJvcnlzZW5rbyBWb3ZhIChVQSkgRGVsZWdhdGUifSwiZW1haWwiOiJib3J5c29mZjIxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJib3J5c2Vua292b2xvZHlteXIiLCJpc3MiOiJodHRwczovL2Rpc2NvcmQuY29tL2FwaSIsIm5hbWUiOiJib3J5c2Vua292b2xvZHlteXIjMCIsIm5lZWRzX29uYm9hcmRpbmciOnRydWUsIm5ld191c2VyIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInBpY3R1cmUiOiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9lbWJlZC9hdmF0YXJzLzAucG5nIiwicHJvdmlkZXJfaWQiOiI2ODgzNjA0MzkyNDI5NDg2MzciLCJzdWIiOiI2ODgzNjA0MzkyNDI5NDg2MzcifSwiaWRlbnRpdGllcyI6W3siaWRlbnRpdHlfaWQiOiIyODQ0ODhiMy1kOTA3LTQxM2UtOGRmMS00OTc3ODZkYWVjZGQiLCJpZCI6IjY4ODM2MDQzOTI0Mjk0ODYzNyIsInVzZXJfaWQiO",
        auth_token1 = "iI5YzY5ODlmYi0yNjU4LTRmN2EtOGE5OC1lZDVhMzBkNjQyYzQiLCJpZGVudGl0eV9kYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9lbWJlZC9hdmF0YXJzLzAucG5nIiwiY3VzdG9tX2NsYWltcyI6eyJnbG9iYWxfbmFtZSI6IkJvcnlzZW5rbyBWb3ZhIChVQSkgRGVsZWdhdGUifSwiZW1haWwiOiJib3J5c29mZjIxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJib3J5c2Vua292b2xvZHlteXIiLCJpc3MiOiJodHRwczovL2Rpc2NvcmQuY29tL2FwaSIsIm5hbWUiOiJib3J5c2Vua292b2xvZHlteXIjMCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwicGljdHVyZSI6Imh0dHBzOi8vY2RuLmRpc2NvcmRhcHAuY29tL2VtYmVkL2F2YXRhcnMvMC5wbmciLCJwcm92aWRlcl9pZCI6IjY4ODM2MDQzOTI0Mjk0ODYzNyIsInN1YiI6IjY4ODM2MDQzOTI0Mjk0ODYzNyJ9LCJwcm92aWRlciI6ImRpc2NvcmQiLCJsYXN0X3NpZ25faW5fYXQiOiIyMDI0LTA4LTE0VDA5OjI5OjMxLjc2Mzg1NFoiLCJjcmVhdGVkX2F0IjoiMjAyNC0wOC0xNFQwOToyOTozMS43NjM5MDJaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDgtMTRUMTQ6MzM6NDQuNDgzMzRaIiwiZW1haWwiOiJib3J5c29mZjIxQGdtYWlsLmNvbSJ9XSwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMTRUMDk6Mjk6MzEuNzU2NzM2WiIsInVwZGF0ZWRfYXQiOiIyMDI0LTA4LTE1VDA5OjQ5OjE1LjUxMjgwNloiLCJpc19hbm9ueW1vdXMiOmZhbHNlfX0",
        captcha_token=captcha_token,
        num_extensions=2,
        custom_lyrics_short="Short song lyrics here",
        custom_lyrics_extend=["Lyrics for first extension", "Lyrics for second extension"],
        custom_lyrics_outro="Outro lyrics here",
        short_prompt=prompt,
        extend_prompts="this is extend prompt",
        outro_prompt="this is an outro prompt"
    )
    return final_song_url
